apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./argocd-roles
  - ./rbac
  - https://github.com/redhat-appstudio/application-service/config/default?ref=1e7aa8103d322cd35e04a8cfa11bbb8b314cb2d0


components:
  - ../k-components/manager-resources
  - ../k-components/enable-profiling

images:
  - name: quay.io/redhat-user-workloads/rhtap-has-tenant/application-service/application-service
    newName: quay.io/redhat-user-workloads/rhtap-has-tenant/application-service/application-service
    newTag: 1e7aa8103d322cd35e04a8cfa11bbb8b314cb2d0

configMapGenerator:
  - literals:
      - GITHUB_ORG=""
    name: github-config
    behavior: replace
  - literals:
      - ENVIRONMENT="development"
    name: feature-flag-config
    behavior: replace


namespace: application-service